version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: bach_hoa_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bach_hoa
      MYSQL_USER: bach_hoa_user
      MYSQL_PASSWORD: bach_hoa_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bach_hoa_network

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bach_hoa_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - bach_hoa_network

  # Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bach_hoa_api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: bach_hoa
      DB_USER: bach_hoa_user
      DB_PASSWORD: bach_hoa_pass
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: your-email@gmail.com
      SMTP_PASS: your-app-password
      UPLOAD_PATH: /app/uploads
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db
    networks:
      - bach_hoa_network

  # Frontend Web App
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bach_hoa_web
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000/api/v1
      VITE_SOCKET_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - bach_hoa_network

volumes:
  mysql_data:

networks:
  bach_hoa_network:
    driver: bridge
